### ISSUE TITLE
sitemap.xmlの生成機能

### ISSUE THREAD

**Issue by Zaty-Tajima** [Zaty-Akiyama/Troms-SEO#6]

**Comment by Zaty-Akiyama** [comment]
# サイトマップを複数に分ける
- post
- page
- custom post
- category
- tag
- custom category
- custom tag
- original url

# 切り替えを設定
- 複数のサイトマップの表示有無を切り替え
- 独自URLを設定してoriginal urlにURLを表示
- 特定のURLのみを削除する設定
